FROM ubuntu:14.04

RUN apt-get update \
    && apt-get install -y cmake curl libgearman-dev

# build opencv

RUN mkdir /build 

# ADD /root/workspace/opencv-3.1.0.tar.gz /build/opencv-3.1.0.tar.gz

RUN wget -O /build/opencv-3.1.0.tar.gz https://github.com/opencv/opencv/archive/3.1.0.tar.gz

RUN cd /build \
		&& tar xzf opencv-3.1.0.tar.gz \		  
    && cd /build/opencv-3.1.0 \
    && cmake . -DWITH_IPP=OFF && make && make install \
    && rm -rf /build

RUN apt-get clean && apt-get autoclean
